export const roles = {
  MODERATOR: {
    actions: [
      "VIEW_CAPITAL_GNG",
      "CREATE_REQUEST",
      "VIEW_REQUEST",
      "VIEW_BCF_REQUEST",
      "CREATE_BCF_REQUEST",
      "CANCEL_REQUEST",
      "CANCEL_BCF_REQUEST",
      "VIEW_HISTORY",
      "VIEW_STORE",
      "VIEW_REPORT",
      "VIEW_REQUESTOR",
      "VIEW_TABLET",
      "VIEW_BCF",
    ],
  },
  ADMIN: {
    actions: [
      "VIEW_CAPITAL_GNG",
      "VIEW_REQUEST",
      "VIEW_BCF_REQUEST",
      "CREATE_BCF_REQUEST",
      "CREATE_REQUEST",
      "CANCEL_REQUEST",
      "CANCEL_BCF_REQUEST",
      "VIEW_HISTORY",
      "VIEW_STORE",
      "CREATE_STORE",
      "EDIT_STORE",
      "VIEW_MERCHANT",
      "CREATE_MERCHANT",
      "EDIT_MERCHANT",
      "VIEW_USER",
      "CREATE_USER",
      "EDIT_USER",
      "VIEW_REPORT",
      "VIEW_REQUESTOR",
      "CREATE_REQUESTOR",
      "EDIT_REQUESTOR",
      "CREATE_TABLET",
      "VIEW_TABLET",
      "DELETE_TABLET",
      "VIEW_BCF",
    ],
  },
  AUDIT: {
    actions: [
      "VIEW_CAPITAL_GNG",
      "VIEW_BCF",
      "VIEW_REQUEST",
      "VIEW_BCF_REQUEST",
      "VIEW_REPORT",
    ],
  },
};
